import { motion } from 'motion/react';
import { ArrowLeft, Database, FileText, CheckCircle, XCircle, HelpCircle, BarChart3 } from 'lucide-react';

interface DatasetPageProps {
  onNavigate: (page: string) => void;
}

export function DatasetPage({ onNavigate }: DatasetPageProps) {
  const stats = [
    { label: 'Total Claims', value: '185,445', icon: <FileText className="w-6 h-6" /> },
    { label: 'Evidence Passages', value: '5.4M', icon: <Database className="w-6 h-6" /> },
    { label: 'Wikipedia Articles', value: '5,396,106', icon: <FileText className="w-6 h-6" /> },
    { label: 'Average Evidence per Claim', value: '1.4', icon: <BarChart3 className="w-6 h-6" /> },
  ];

  const examples = [
    {
      claim: "Robert Downey Jr. played the role of Tony Stark in the Marvel Cinematic Universe.",
      evidence: "Iron Man is a 2008 American superhero film based on the Marvel Comics character of the same name, produced by Marvel Studios and distributed by Paramount Pictures. It is the first film in the Marvel Cinematic Universe. The film was directed by Jon Favreau, with a screenplay by Mark Fergus and Hawk Ostby, and Art Marcum and Matt Holloway. Robert Downey Jr. stars as Tony Stark.",
      label: "SUPPORTS",
      icon: <CheckCircle className="w-5 h-5 text-green-500" />
    },
    {
      claim: "The Eiffel Tower was built in Rome, Italy.",
      evidence: "The Eiffel Tower is a wrought iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower. Constructed from 1887–89 as the entrance to the 1889 World's Fair.",
      label: "REFUTES",
      icon: <XCircle className="w-5 h-5 text-red-500" />
    },
    {
      claim: "Quantum computing will revolutionize cryptography within 5 years.",
      evidence: null,
      label: "NOT ENOUGH INFO",
      icon: <HelpCircle className="w-5 h-5 text-yellow-500" />
    }
  ];

  return (
    <div className="min-h-screen">
      {/* Header */}
      <div className="bg-neutral-900/50 backdrop-blur-sm border-b border-neutral-800">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center gap-4">
          <button
            onClick={() => onNavigate('landing')}
            className="text-neutral-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-6 h-6" />
          </button>
          <h1 className="text-white">FEVER Dataset</h1>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-12">
        {/* Overview */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-neutral-900/50 backdrop-blur-sm border border-neutral-800 rounded-2xl p-8 mb-12"
        >
          <div className="flex items-start gap-6">
            <div className="p-4 bg-[#500000] rounded-xl">
              <Database className="w-8 h-8 text-white" />
            </div>
            <div className="flex-1">
              <h2 className="text-white mb-4">FEVER: Fact Extraction and VERification</h2>
              <p className="text-neutral-300 mb-4">
                FEVER is a publicly available dataset for fact extraction and verification against 
                textual sources. It consists of 185,445 claims generated by human annotators from 
                Wikipedia, each labeled as SUPPORTED, REFUTED, or NOTENOUGHINFO.
              </p>
              <p className="text-neutral-300">
                This dataset is ideal for information retrieval research because it requires systems 
                to both retrieve relevant evidence from a large corpus and understand the semantic 
                relationship between claims and evidence passages.
              </p>
            </div>
          </div>
        </motion.div>

        {/* Statistics */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12"
        >
          {stats.map((stat, index) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.2 + index * 0.1 }}
              className="bg-neutral-900/50 backdrop-blur-sm border border-neutral-800 rounded-2xl p-6 hover:border-[#500000] transition-all"
            >
              <div className="text-[#500000] mb-3">{stat.icon}</div>
              <div className="text-3xl text-white mb-2">{stat.value}</div>
              <div className="text-neutral-400">{stat.label}</div>
            </motion.div>
          ))}
        </motion.div>

        {/* Example Claims */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="mb-12"
        >
          <h2 className="text-white mb-6">Example Claim-Evidence Pairs</h2>
          <div className="space-y-6">
            {examples.map((example, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.4 + index * 0.1 }}
                className="bg-neutral-900/50 backdrop-blur-sm border border-neutral-800 rounded-2xl p-6"
              >
                <div className="flex items-start gap-3 mb-4">
                  {example.icon}
                  <div>
                    <span className={`px-3 py-1 rounded-lg text-white ${
                      example.label === 'SUPPORTS' ? 'bg-green-600' :
                      example.label === 'REFUTES' ? 'bg-red-600' :
                      'bg-yellow-600'
                    }`}>
                      {example.label}
                    </span>
                  </div>
                </div>

                <div className="mb-4">
                  <div className="text-neutral-400 mb-2">Claim:</div>
                  <p className="text-white bg-neutral-800 p-4 rounded-lg">
                    "{example.claim}"
                  </p>
                </div>

                {example.evidence ? (
                  <div>
                    <div className="text-neutral-400 mb-2">Evidence:</div>
                    <p className="text-neutral-300 bg-neutral-800 p-4 rounded-lg">
                      {example.evidence}
                    </p>
                  </div>
                ) : (
                  <div className="text-neutral-400 bg-neutral-800 p-4 rounded-lg italic">
                    No sufficient evidence found in the corpus
                  </div>
                )}
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Why FEVER for IR */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.7 }}
          className="bg-neutral-900/50 backdrop-blur-sm border border-neutral-800 rounded-2xl p-8 mb-8"
        >
          <h2 className="text-white mb-6">Why FEVER is Relevant for Information Retrieval</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <RelevanceCard
              title="Large-Scale Corpus"
              description="With 5.4M Wikipedia articles, FEVER provides a realistic search space that mirrors real-world IR challenges at scale."
            />
            <RelevanceCard
              title="Semantic Understanding Required"
              description="Success requires understanding paraphrases, synonyms, and semantic relationships—not just keyword matching."
            />
            <RelevanceCard
              title="Multi-Hop Reasoning"
              description="Some claims require combining evidence from multiple passages, testing complex retrieval strategies."
            />
            <RelevanceCard
              title="Established Benchmarks"
              description="FEVER is widely used in IR research, allowing direct comparison with state-of-the-art systems."
            />
            <RelevanceCard
              title="Diverse Query Types"
              description="Claims span various topics and complexity levels, from simple factual lookups to complex reasoning."
            />
            <RelevanceCard
              title="Ground Truth Labels"
              description="Human-annotated labels enable rigorous evaluation of retrieval effectiveness and ranking quality."
            />
          </div>
        </motion.div>

        {/* Dataset Splits */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.9 }}
          className="bg-neutral-900/50 backdrop-blur-sm border border-neutral-800 rounded-2xl p-8"
        >
          <h2 className="text-white mb-6">Dataset Splits</h2>
          <div className="space-y-4">
            <DatasetSplit
              name="Training Set"
              claims="145,449"
              percentage="78.4%"
              color="#10b981"
            />
            <DatasetSplit
              name="Development Set"
              claims="19,998"
              percentage="10.8%"
              color="#f59e0b"
            />
            <DatasetSplit
              name="Test Set"
              claims="19,998"
              percentage="10.8%"
              color="#ef4444"
            />
          </div>

          <div className="mt-6 p-4 bg-neutral-800 rounded-lg">
            <p className="text-neutral-300">
              <span className="text-[#500000]">Note:</span> Our MosaicRetriever system was 
              trained on the training set, tuned on the development set, and final metrics 
              reported on the held-out test set to ensure fair evaluation.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}

interface RelevanceCardProps {
  title: string;
  description: string;
}

function RelevanceCard({ title, description }: RelevanceCardProps) {
  return (
    <div className="p-4 bg-neutral-800 rounded-xl">
      <h3 className="text-[#500000] mb-2">{title}</h3>
      <p className="text-neutral-300">{description}</p>
    </div>
  );
}

interface DatasetSplitProps {
  name: string;
  claims: string;
  percentage: string;
  color: string;
}

function DatasetSplit({ name, claims, percentage, color }: DatasetSplitProps) {
  return (
    <div className="flex items-center gap-4">
      <div className="flex-1">
        <div className="flex items-center justify-between mb-2">
          <span className="text-white">{name}</span>
          <span className="text-neutral-400">{claims} claims ({percentage})</span>
        </div>
        <div className="h-2 bg-neutral-700 rounded-full overflow-hidden">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: percentage }}
            transition={{ duration: 1, delay: 0.5 }}
            className="h-full rounded-full"
            style={{ backgroundColor: color }}
          />
        </div>
      </div>
    </div>
  );
}
